version: '3.7'
services:

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adm_videos
#      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
#    volumes:
#      - ../.docker/mysql:/var/lib/mysql:rw
    networks:
      - adm_videos_network
networks:
  adm_videos_network:
    driver: bridge

#  keycloak:
#    container_name: adm_videos_keycloak
#    image: quay.io/keycloak/keycloak:20.0.3
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    ports:
#      - 8443:8080
#    command:
#      - start-dev # Utilizar esse comando quando a aplicação estiver executando fora do Docker
#    #      - start-dev --hostname-url=http://keycloak:8080 # Utilizar esse comando quando a aplicação estiver dentro do Docker
#    volumes:
#      - ../.docker/keycloak:/opt/keycloak/data/h2:rw
#    networks:
#      - adm_videos_services

